#!/bin/bash
set -x
usage() {
    echo "$0 [outfile]"
    echo "$0 will run until it receives a SIGTERM or SIGINT."
    echo "Once a SIGINT/TERM is received, the captured video will be"
    echo "converted to a gif at the specified location."
}

writegif() {
    kill $FFMPEG_PID
    wait $FFMPEG_PID
    notification_id=$(dunstify -p -t 900000 -a "$0" 'Screencast' 'Generating GIF')
    convert -set delay 10 -layers Optimize $TMPFILE $OUTPUT
    dunstify -C "${notification_id}"
    rm $TMPFILE
}

if [ -z $1 ]; then
    usage
    exit 1
fi

OUTPUT=$1
TMPFILE="$(mktemp -t screencast-XXXXXXX.avi)"
trap writegif EXIT SIGTERM SIGINT
read -r X Y W H G ID < <(slop -f "%x %y %w %h %g %i")
ffmpeg -y -f x11grab -framerate 15 -s "$W"x"$H" -i :0.0+$X,$Y -codec:v huffyuv "$TMPFILE" &
FFMPEG_PID=$!
dunstify -b -a "$0" -t 900000 --action="stop,Stop Recording" "Screencast" "Capturing screen. Dismiss notification to stop recording"
